version: '1'  #version of docker-compose
services:
  my-app:
    image: 129350621020.dkr.ecr.ap-southeast-2.amazonaws.com/my-app:1.0
    ports:
      - 3000:3000
  mongo:
    image: mongo  #docker image
    container_name: mongodb  #Contrainer name
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:  #open ports
     - 27017:27017  #HOST:CONTAINER
  mongo-express:
    image: mongo-express   #docker image
    container_name: mongo-express  #Contrainer name
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/